server:
  port: 8025
  
spring:
  application:
    name: student_management
  datasource:
    url: jdbc:postgresql://localhost:5432/student_management?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: soft@123!@#
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    ROOT: INFO
    com.parsa.erp.accounting: INFO
  file:
    path: /home/software/student_management/logs
